### ISSUE TITLE
call any anchor program instruction

### ISSUE THREAD

**Issue by setmax** [bmresearch/Solnet#367]
i wrote a program with anchor, so I want to call my program instruction with solnet. is there any example of that?

**Comment by setmax** [comment]
I saw that. I cloned a simple anchor example from this [repo](https://github.com/project-serum/anchor/tree/master/examples/tutorial/basic-2)
after that, I build it, and according to your instruction

> dotnet tool install Solnet.Anchor.Tool (if you use -g option, you won't need to do this for every project')
dotnet anchorgen -i idl/file.json -o src/ProgramCode.cs
You can generate from a live program that uploaded its idl using flag -a, or add the default program address if used alongside -i
You stdout output is supported using -s flag

i wanted to use  generator tool with this command:
`dotnet-anchorgen -i idl/inc.json -o anchor-gen/source.sc`

so i saw this error:

> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Solnet.Anchor.ClientGenerator.GenerateErrorsSyntaxTree(Idl idl) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor/ClientGenerator.cs:line 2192
   at Solnet.Anchor.ClientGenerator.GenerateSyntaxTree(Idl idl) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor/ClientGenerator.cs:line 63
   at Solnet.Anchor.ClientGenerator.GenerateCode(Idl idl) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor/ClientGenerator.cs:line 89
   at AnchorSourceGenerator.<>c.<Main>b__0_1(CommandLineOptions opts) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor.Tool/AnchorSourceGenerator.cs:line 56
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at AnchorSourceGenerator.Main(String[] args) in /home/runner/work/Solnet.Anchor/Solnet.Anchor/Solnet.Anchor.Tool/AnchorSourceGenerator.cs:line 19
Aborted

any idea?
